language: node_js
node_js:
  - "6"
branches:
  only:
  - hexo
before_install:
- openssl aes-256-cbc -K $encrypted_8b4d90e9ac0d_key -iv $encrypted_8b4d90e9ac0d_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp ssh_config ~/.ssh/config
- git config --global user.name "Melos"
- git config --global user.email imelosun@gmail.com
install:
- npm install hexo-cli -g
- npm install
- npm install hexo-generator-feed --save
- npm install hexo-deployer-git --save
- npm install hexo-generator-json-content --save
script:
- hexo clean
- hexo g
- hexo d
